// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace macdoc {
	
	
	// Should subclass MonoMac.AppKit.NSDocument
	[MonoMac.Foundation.Register("MyDocument")]
	public partial class MyDocument {
		
		private global::MonoMac.AppKit.NSSegmentedCell __mt_navigationCells;
		
		private global::MonoMac.AppKit.NSOutlineView __mt_outlineView;
		
		private global::MonoMac.AppKit.NSOutlineView __mt_searchResults;
		
		private global::MonoMac.WebKit.WebView __mt_webView;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Connect("navigationCells")]
		private global::MonoMac.AppKit.NSSegmentedCell navigationCells {
			get {
				this.__mt_navigationCells = ((global::MonoMac.AppKit.NSSegmentedCell)(this.GetNativeField("navigationCells")));
				return this.__mt_navigationCells;
			}
			set {
				this.__mt_navigationCells = value;
				this.SetNativeField("navigationCells", value);
			}
		}
		
		[MonoMac.Foundation.Connect("outlineView")]
		private global::MonoMac.AppKit.NSOutlineView outlineView {
			get {
				this.__mt_outlineView = ((global::MonoMac.AppKit.NSOutlineView)(this.GetNativeField("outlineView")));
				return this.__mt_outlineView;
			}
			set {
				this.__mt_outlineView = value;
				this.SetNativeField("outlineView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("searchResults")]
		private global::MonoMac.AppKit.NSOutlineView searchResults {
			get {
				this.__mt_searchResults = ((global::MonoMac.AppKit.NSOutlineView)(this.GetNativeField("searchResults")));
				return this.__mt_searchResults;
			}
			set {
				this.__mt_searchResults = value;
				this.SetNativeField("searchResults", value);
			}
		}
		
		[MonoMac.Foundation.Connect("webView")]
		private global::MonoMac.WebKit.WebView webView {
			get {
				this.__mt_webView = ((global::MonoMac.WebKit.WebView)(this.GetNativeField("webView")));
				return this.__mt_webView;
			}
			set {
				this.__mt_webView = value;
				this.SetNativeField("webView", value);
			}
		}
	}
}
