@interface CISampler : NSObject <NSCopying>
extern NSString *kCISamplerAffineMatrix AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER;
extern NSString *kCISamplerWrapMode AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER;
extern NSString *kCISamplerFilterMode AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER;
extern NSString *kCISamplerWrapBlack, *kCISamplerWrapClamp AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER;
extern NSString *kCISamplerFilterNearest, *kCISamplerFilterLinear AVAILABLE_MAC_OS_X_VERSION_10_4_AND_LATER;
